### ISSUE TITLE
Survived vs. Sex graph in keggle titanic dataset

### ISSUE THREAD

**Issue by shubham-singh-ss** [mrdbourke/your-first-kaggle-submission#1]
by writing the same code, I'm getting a different graph for survived vs sex graph. 

Pl. have a look into it. Where did I do wrong?

**Comment by shubham-singh-ss** [comment]
![screenshot from 2019-03-06 04-31-23](https://user-images.githubusercontent.com/26729181/53843529-c0abbb80-3fc8-11e9-9cd1-ba68926ccc28.png)

**Comment by ayePete** [comment]
Same here. I have no idea why this is the case. Also, the colors are different in my case (blue and green, which are much less distinct)

**Comment by mrdbourke** [comment]
@shubham-singh-ss There was an update to the Seaborn library which changed the look of the graph. My colours are still blue and orange though.

Have you tried changing the colour palette @ayePete? This link might help: https://seaborn.pydata.org/tutorial/color_palettes.html
